### ISSUE TITLE
Distance and scale variables

### ISSUE THREAD

**Issue by dlewand691** [terwanerik/ScrollTrigger#10]
**Suggestion:** Add in and out variables to set:

1. animation distance
2. scale
3. speed

**Comment by terwanerik** [comment]
The idea of ScrollTrigger was/is to do all that stuff in CSS, keeping the JavaScript load as low as possible. Do you have any use cases where this can't be done with CSS?

**Comment by dlewand691** [comment]
Oh, I was of course thinking the variables could be set in SASS to give the flexibility of how dramatic or subtle the movements could be. No need to overload the javascript any more than necessary.

**Comment by terwanerik** [comment]
Great! Closing this for now :)
