### ISSUE TITLE
timed delays

### ISSUE THREAD

**Issue by SimonFricker** [terwanerik/ScrollTrigger#12]
Add a time delay parameter eg data-scroll-delay=".5s" or data-scroll-delay="1.5s"

**Comment by terwanerik** [comment]
I'm going to [reference this comment right here](https://github.com/terwanerik/ScrollTrigger/issues/10#issuecomment-230601317); If you find use cases where this cannot be done with css or implemented in the js callback, i'll consider it.

**Comment by SimonFricker** [comment]
I could have an animation heavy website where many delays would be needed. This can get very tedious to write in CSS. See an example here: https://github.com/SimonFricker/delay.css/blob/master/delay.css - thus generating the CSS delay on the fly is a better option.

**Comment by MikeHarrison** [comment]
That might be a good place to use a SASS mixin, rather than change the js:

```
@mixin animation-delay($time) {
    animation-delay: $time;
    -moz-animation-delay: $time;
    -webkit-animation-delay: $time;
    -o-animation-delay: $time;
    transition-delay: $time;
    -webkit-transition-delay: $time;
    -moz-transition-delay: $time;
    -o-transition-delay: $time;
}

.thing { @include animation-delay(1.2s); }
```

**Comment by terwanerik** [comment]
I'm with MikeHarrison on this one. Plus; if you use [autoprefixer](https://autoprefixer.github.io) you would only have to write 1 line of code per animation, doing this in a html attribute would be almost as much work.

**Comment by SimonFricker** [comment]
While I do agree with MikeHarrison also I can see use cases where the user would not be writing the CSS and can only control variables in the DOM, eg the end user of a custom WordPress theme.  I think not developing the feature will result is less adoption of ScrollTrigger
