### ISSUE TITLE
Jumping when URL bar disappears on Android 

### ISSUE THREAD

**Issue by Sandstedt** [terwanerik/ScrollTrigger#13]
The demo page jumps up and down a hole section when scrolling so the URL bar hides and shows (on Android, hasn't tried on iOS). I guess because the viewport height is changing when the URL bar hides or shows, and some calculations of the pages scroll position is based on the viewport size. 

The bug is more visible in Chrome then in Firefox.

**Comment by tornography** [comment]
As you mentioned, Sandstedt, this is a browser behaviour. Not really a bug of the script.

I don't think the script should interfere with that behaviour. But a fix I used to use is to grab the initial height of the element, and add this as fixed height to that element. This way there is no re-draw when the url bar hides.

**Comment by dimitrieh** [comment]
you may find some info here: http://stackoverflow.com/questions/24944925/background-image-jumps-when-address-bar-hides-ios-android-mobile-chrome

**Comment by terwanerik** [comment]
Completly agree with tornography, closing this
