### ISSUE TITLE
scrollmagic

### ISSUE THREAD

**Issue by dimitrieh** [terwanerik/ScrollTrigger#14]
Is it possible to do scroll magic like tweening with this plugin, which reacts live to scrolling, not just triggers ;) #curious

**Comment by terwanerik** [comment]
You can hook up to the update loop by using the attach method, checkout readme for more info. I will post a more detailed example when i get back from vacation! You should be able to do what you described.

**Comment by dimitrieh** [comment]
followup question ;) is this lib lighter than scrollmagic :) performance wise etc
