### ISSUE TITLE
Use IntersectionObserver for better future performance.

### ISSUE THREAD

**Issue by birkir** [terwanerik/ScrollTrigger#15]
IntersectionObserver is way faster than hooking into the scroll.

Then add the polyfill 👍 

https://github.com/WICG/IntersectionObserver/pull/135

**Comment by terwanerik** [comment]
Not hooking on to the onscroll event at all! Using requestAnimationFrame, way more preformant than the 100ms delay used in the IntersectionObserver polyfill you posted. IntersectionObserver is looking promising, but i will hold off on implementing untill it's supported on all mayor browsers. 

Thanks for the heads up!

**Comment by johanneslamers** [comment]
Any updates on this? http://caniuse.com/#feat=intersectionobserver. 63% can use this.
