### ISSUE TITLE
Horizontal scrolling - text blocks not appearing on Android Lolipop 

### ISSUE THREAD

**Issue by brianyerkes** [terwanerik/ScrollTrigger#16]
I'm presuming there are text blocks in the various sections as your scroll horizontally. They don't load for me on Lollipop 5.0.1 / Chrome / Samsung Galaxy S4.  Vertical scroll works very nicely,  am exit with the jump due to the address bar issue

**Comment by terwanerik** [comment]
Could you create a [minimal, complete and verifiable example](http://stackoverflow.com/help/mcve)? And upload that to codepen.io or something like that?

Thanks!

**Comment by brianyerkes** [comment]
The issue I was describing was on your demo.

**Comment by terwanerik** [comment]
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.
