### ISSUE TITLE
Make it possible to trigger javascript functions

### ISSUE THREAD

**Issue by skttl** [terwanerik/ScrollTrigger#2]
Maybe a possibility to trigger javascript functions when element comes into view.

Like <div data-scroll-visible="doSomething()" data-scroll-invisible="doSomethingElse()"></div>

**Comment by terwanerik** [comment]
Yeah i like this idea, just figuring out what the best syntax would be. I'm thinking something like `data-scrollCall="foo('bar')"`, that way it doesn't clutter the default scroll attribute. Ideas?

**Comment by skttl** [comment]
I think it would be best to have separate attributes for that, and maybe also for the other settings. It makes the syntax easier to understand and less error prone.

**Comment by terwanerik** [comment]
I added this functionality in the [v0.2-new-syntax](https://github.com/terwanerik/ScrollTrigger/tree/v0.2-new-syntax) branch, checkout the example directory on how-to implement.

Merging this branch tomorrow, need to write the new readme first.
