### ISSUE TITLE
Problem with multiple instances in the viewport

### ISSUE THREAD

**Issue by Stenvdb** [terwanerik/ScrollTrigger#20]
There's a problem with multiple instance in the same viewport where the once option is set to true. It removes the trigger after showing it here on line 372:

```
// remove trigger from triggers array
triggers.splice(i, 1);
```

This causes a change in the length of the triggers array and so the for loop doesn't loop over all the triggers thus not showing all instances. I've fixed this by adding an extra internal option 'shown' to the trigger object and set that to true instead of removing that trigger from the array. Then I wrapped the entire block inside that loop in  `if(!trigger.shown)`

Maybe this is not the best approach, but it works for me now.

**Comment by terwanerik** [comment]
Hm sounds strange, could you create a [minimal, complete and verifiable example](http://stackoverflow.com/help/mcve)? And upload that to codepen.io or something like that?

Thanks!

**Comment by terwanerik** [comment]
> This causes a change in the length of the triggers array and so the for loop doesn't loop over all the triggers thus not showing all instances.

That should not be possible since it loops every time you scroll / the animation frame is executed; so the size change in the `for` loop should not be an issue.

**Comment by terwanerik** [comment]
I just updated to v0.3.3 and added a removalQueue, this should prevent this behaviour.
