### ISSUE TITLE
Advanced Animation - Example

### ISSUE THREAD

**Issue by ndimatteo** [terwanerik/ScrollTrigger#21]
I was able to setup an advanced animation pretty quickly, which you can preview here: http://nickdimatteo.com/scrollTrigger/example/

I'm curious if (1) this is your recommended solution for such a case, and (2) to take a look on mobile, since it appears sometimes if you scroll too fast the top section fades in/out when it shouldn't.

**Comment by terwanerik** [comment]
Sorry for the late reaction, just came back from vacation.

Yeah i would say this is a proper implementation of the `.attach()` method, looks good! I'm not having any issues on mobile either.
