### ISSUE TITLE
Use of .invisible as the class

### ISSUE THREAD

**Issue by 4pixels** [terwanerik/ScrollTrigger#22]
Can you change the class .invisible to say .trigger-invisible (and trigger-visible) as Bootstrap already uses .invisible to hide elements.

**Comment by influxweb** [comment]
You can set the classes you would like to use in the 'toggle' attribute when you initialize the function:
```javascript
toggle: {
  visible: 'visibleClass',
  hidden: 'hiddenClass'
},
```

**Comment by 4pixels** [comment]
Thank you influxweb.
