### ISSUE TITLE
How can I refresh scrollTrigger?

### ISSUE THREAD

**Issue by ndimatteo** [terwanerik/ScrollTrigger#23]
I'm using scrollTrigger on a site that uses pjax, and it works great, except when I use the "once" option with a trigger.

Since a trigger is removed from the triggers array in this case, there's no way to for me to refresh/recollect those triggers later.

There should be a re-init/refresh method to call otherwise my triggers that are set to show once don't ever work again in an ajax environment.

**Comment by ndimatteo** [comment]
Also would be good to have some sort of destroy() method.

**Comment by terwanerik** [comment]
Yeah i like this idea, i'll implement this (hopefully) this weekend.

**Comment by ndimatteo** [comment]
Thanks! Looking forward to it :)

**Comment by ndimatteo** [comment]
Any updates on this? Would love to get this implemented so I can tie up some issues with my projects using scrollTrigger :)

**Comment by terwanerik** [comment]
Fixed all these issues! Check the [release](https://github.com/terwanerik/ScrollTrigger/releases/tag/v0.3.2) for more info. 

Thanks for the input!

**Comment by ndimatteo** [comment]
Thanks @terwanerik, but it doesn't seem to be working?

I'm calling ```.resetAll()``` on the instance and now my scrollTriggers don't react to anything at all.

To elaborate, I left my code the same, and simply updated the scrollTrigger script and called the ```.resetAll()``` when my content loads. This kills the scrollTriggers.

You can check it here: http://dev.nickdimatteo.com/twenty-over-ten

I know that it's being called because I console.logged where it's being called and you can see it logs properly. Any ideas?

Really love this script and would love to wrap this up, thanks!

**Comment by ndimatteo** [comment]
Apologies @terwanerik I think I was misunderstanding the new methods, can you confirm that this would be the best way to **refresh** my scrollTriggers?

````javascript
scrollTrigger.resetAll().bind(document.querySelectorAll('[data-scroll]'));
````

**Comment by terwanerik** [comment]
Yeah that would be a way, even faster would be `destroyAll` instead of `resetAll`.
