### ISSUE TITLE
Callbacks don't work with nested functions

### ISSUE THREAD

**Issue by voidstate** [terwanerik/ScrollTrigger#26]
I have been trying to organise my callbacks into an object to avoid polluting the window namespace but have found that ScrollTrigger cannot call them.

This fails:

`data-scroll-showCallback="myProject.doStuff"`

I have also found that there is a problem with passing arguments - I think this is because you are using call when you should be using apply.

So, on line 613, this:

`window[method].call(trigger.element,` params);`

should read:

`window[method].apply(trigger.element,` params);`

Call only takes parameters not a node to apply the function to.

**Comment by terwanerik** [comment]
Yeah they had to be in the window scope. I changed this now, pushing a new version out in a couple of minutes. 

Also, using `.call` was intentional, the system was built for just one attribute. This is also fixed in the new version, allowing for as many attributes as you like.

**Comment by terwanerik** [comment]
Done! Checkout [https://github.com/terwanerik/ScrollTrigger/releases/tag/v0.3.5](the most recent release) for a quick instruction. Proper documentation is on it's way.
