### ISSUE TITLE
No trigger when element is out of the viewport (on the left side)

### ISSUE THREAD

**Issue by jeremylemardele** [terwanerik/ScrollTrigger#27]
Hello,

I have an issue with all the elements that are a bit out of the viewport, on the left.
For instance, if a div has the following style: "transform: translateX(-20px)", nothing will be triggered.

Thank you for your help.
Best regards,
Jeremy

**Comment by terwanerik** [comment]
Hi,

Could you create a [minimal, complete and verifiable example](http://stackoverflow.com/help/mcve) and upload that to [codepen](http://codepen.io)?

Thanks!

**Comment by jeremylemardele** [comment]
Here you are: http://codepen.io/jeremylemardele/pen/wgNypy

By the way, since then I changed my strategy, so this is not a problem to me anymore.

**Comment by terwanerik** [comment]
Thanks! Yes this is expected behaviour, since the element is not in the viewport. You can use `data-scroll="offset(80px,0)"` to offset the calculation as if it is in the viewport.
