### ISSUE TITLE
overflow-x: hidden chrome problem

### ISSUE THREAD

**Issue by jozkohuzko** [terwanerik/ScrollTrigger#30]
Hi, 
got problem when "overflow-x: hidden" is set for html, body the scrolltrigger is not working in chrome browser. In other browsers is everything working smoothly.

thanks

**Comment by terwanerik** [comment]
I'm assuming it has something to do with [this bug](https://github.com/jquery/jquery/issues/2215). Can you remove `overflow-x: hidden` from the `html` element and just place it on the `body` element?

**Comment by terwanerik** [comment]
I'd reckon it had to to with the Chrome bug. Closing this for now.
