### ISSUE TITLE
Allow use multiple classes in toogle

### ISSUE THREAD

**Issue by evilebottnawi** [terwanerik/ScrollTrigger#32]
```html
data-scroll="toggle(.animated .boundIn, .animated .boundOut)"
```

**Comment by terwanerik** [comment]
Yeah i like the idea of this, i'll implement this in a future version.

**Comment by terwanerik** [comment]
I've added this to [New features in v3.0](https://github.com/terwanerik/ScrollTrigger/issues/37)
