### ISSUE TITLE
How do I pass arguments or parameters to the callback function?

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [terwanerik/ScrollTrigger#34]
Hi there,

Thanks for the great script!

I have a problem that I've not been able to figure out yet. I want to be able to pass arguments to the `data-scroll-showCallback` function. Specifically, I would like to pass: 1) the HTML element that contains the `data-scroll-showCallback` attribute as the first argument; 2) a number; and 3) a Boolean.

Thank you for any help you can provide,
Jeremy

**Comment by terwanerik** [comment]
Hi,

The html element is passed as `this`, the parameters are given as an array. So:
`data-scroll-showCallback="myFunction(1, 'something')"` calls:
```
function myFunction(number, string) {
  this.addClass('something') // this is the html element
  alert(number);
  alert(string);
}
```
