### ISSUE TITLE
Delay OUT class until the element leaves viewport

### ISSUE THREAD

**Issue by wgstjf** [terwanerik/ScrollTrigger#36]
Hi,

Loving this plugin, thanks!

Just a quick one - is there an easy way to prevent the 'out' class being assigned to the element until after it has left the viewport?

We have panels that we are animating the text up (and fading in) when it comes into the viewport but would like to prevent the fade out and drop down until after the block has completely left the user's viewport.

Sorry - one other thing - If an element is absolutely positioned to the left and then translated on the X axis with a negative percentage value, such as:

```css
position:absolute;
left:0;
transform: translateX(-3%);
```

I cannot get the scrollTrigger to trigger.  I see from another post that you recommend adding an offset but I can't get this to work with a percentage (used instead of px due to responsive nature).  Any thoughts on this would be much appreciated too. :-)

Cheers,

Will

**Comment by terwanerik** [comment]
You can set 'addHeight' to prevent it from setting the classes until after it has completely left the viewport, the thing is that it doesn't separate the positioning with entering and leaving the viewport right now. So you'll only see the animation happening once the element has entered the viewport completely as well.

Working with percentages in the offset is not supported right now.. You might be able to program it in yourself, take a look at ScrollTrigger.js, the code is not that difficult ;)

I'm thinking of making ScrollTrigger 3.0 a lot more JS dependant than working with attributes, making it more customisable.

I added this issue to [New features in v3.0](https://github.com/terwanerik/ScrollTrigger/issues/37)

**Comment by wgstjf** [comment]
Thanks for the quick reply.  Will have a go at a few mods and keep a look out for v3.0

Cheers.
