### ISSUE TITLE
custom data-scroll-showCallback="drawIt()" not firing

### ISSUE THREAD

**Issue by thaoms** [terwanerik/ScrollTrigger#41]
My custom callback is not firing when the item is already in view on refresh, it only fires when I do a little scrolling.

I see that the visible class is added on init, so it's specific to the custom callback.

**Comment by terwanerik** [comment]
When are you setting the custom callback? How are you initializing the triggers?

**Comment by thaoms** [comment]
I tried both scopes, but they give the same results.

Im setting the callback like this;
I tried removing the 'once' param and simulated it with a variable but no luck.

Chart is a chart.js plugin


`<canvas data-scroll-showCallback="drawIt()" data-scroll id="myChart" class="pie-chart" width="290" height="290"></canvas>`

```
const trigger = new ScrollTrigger({
			toggle: {
				visible: 'visibleClass',
				hidden: 'hiddenClass'
			}
		});
		let first = true;

		// triggered when in view
		window.drawIt = function() {
			if(first){
				myChart.update();
				first = false;
			}

		};```

**Comment by terwanerik** [comment]
Alright, and when you place define the callback first, and then initialize ScrollTrigger? E.g;

```
let first = true;

// triggered when in view
window.drawIt = function() {
	if(first){
		myChart.update();
		first = false;
	}
};

const trigger = new ScrollTrigger({
	toggle: {
		visible: 'visibleClass',
		hidden: 'hiddenClass'
	}
});
```

**Comment by thaoms** [comment]
That fixed it, so easy I didn't even see it.

Thank you!

**Comment by terwanerik** [comment]
Great, you could probably just set `myChart` as the `callScope` and just set `data-scroll-showCallback` to `update()` ;)
