### ISSUE TITLE
IT IS NOT AN ISSUE. JUST WANTED TO SAY THANK YOU

### ISSUE THREAD

**Issue by Zakrok09** [terwanerik/ScrollTrigger#42]
You guys are the best ones around. It took me ages to find smt like this data-scroller trigger and i found yours. It is really simple and fantastic.

**Comment by terwanerik** [comment]
Haha thanks! Good to hear you like it :) There is no donation button, but i do have a [PayPal.me](https://PayPal.Me/ErikTerwan) link if you'd wish to donate. Please keep in mind that i do this project for fun, so donations are not necessary ;)
