### ISSUE TITLE
Can't access the html element in custom animations

### ISSUE THREAD

**Issue by fredericpfisterer** [terwanerik/ScrollTrigger#43]
I tried with "this" but it does not work :

`document.addEventListener('DOMContentLoaded', function(){
  var trigger = new ScrollTrigger();

  var callback = function(scrollLeft, scrollTop, width, height){
    console.log(this);
    trigger.detach(callback);
  };

  trigger.attach(callback);
});`

Any ideas what I'm doing wrong ?

**Comment by fredericpfisterer** [comment]
I have created a codepen so you can see :

https://codepen.io/fredericpfisterer/pen/VXQYzm/

**Comment by terwanerik** [comment]
Ah the documentation is a bit crooked here, the `trigger.attach` method is only to link into the `window.requestAnimationFrame` loop. References to the triggers/html elements are not passed here. If you want to have a callback you should checkout the [callbacks](https://github.com/terwanerik/ScrollTrigger#callbacks) section. 

I [updated your example](https://codepen.io/erikterwan/pen/RMQQWQ).

**Comment by fredericpfisterer** [comment]
Thanks for your answer but now I'm getting the container. Is there a way to actually get the .box element ?

**Comment by terwanerik** [comment]
If you checkout the [updated example](https://codepen.io/erikterwan/pen/RMQQWQ), and open up your console, you'll notice that you get the `<div class="box" data-scoll...>` element, right?

**Comment by fredericpfisterer** [comment]
Yes, you are correct. Sorry for the confusion. Thanks :-)

**Comment by terwanerik** [comment]
No problem ;)
