### ISSUE TITLE
Not compatible with safari

### ISSUE THREAD

**Issue by nightire** [terwanerik/ScrollTrigger#47]
These two lines not works in safari, because safari doesn't respect `document.documentElement.scrollTop/Left`

https://github.com/terwanerik/ScrollTrigger/blob/56b4b04695ad3be2d69aa406cfd88746d194192f/ScrollTrigger.js#L548-L549

This is a complicated topic, so I just put a reference here, it is up to you to decide choose which solution: https://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome/33462363#33462363

**Comment by terwanerik** [comment]
What version of safari are you using?

**Comment by nightire** [comment]
@terwanerik version12. I should make it clear: in Safari, it has `document.documentElement.scrollTop/Left` property, however its value is always `0`, this is what I mean of saying "not working".

**Comment by terwanerik** [comment]
Alright, the thing is; it checks if a `bindElement` is given, which standards to `body`. document.body.scrollTop/Left works perfectly in Safari, so that line should not be called on Safari. Is there a minimal, complete and verifiable example where it isn't working?

**Comment by nightire** [comment]
@terwanerik Alright, I think I know what's going on. I didn't write the original code, it was written by one of my colleagues. After read your comment, I checked the source code where `ScrollTrigger` has initialized, then I realized he use a specific node instead of `window` as the `bindElement`.

As a result, this node's `scrollTop` is always `0`, so this clause will return `document.documentElement.scrollTop` which "not working" in Safari as I described at the beginning.

Now my question becomes: is it allowed to passing arbitrary element instead of `window` as `bindElement`?

P.S. I don't know why he did that, but I'd prefer to not change his original code first.

**Comment by terwanerik** [comment]
Ah alright i see, yeah the `bindElement` is used when you want to trigger classes inside a scrolling div.

For example (untested code);

```html
<div class="wrap">
  <div data-scroll></div>
  <div data-scroll></div>
  <div data-scroll></div>
</div>
```

```css
.wrap {
  height: 500px;
  overflow-y: scroll;
}

.wrap div[data-scroll] {
  height: 300px;
  width: 100%;
  background: red;
}
```

```javascript
var wrapper = document.querySelector('.wrap');

/** 
  * First parameter = options
  * Second parameter = bindElement (where to fetch the [data-scroll] elements from)
  * Last parameter = the element to listen for `scroll` event, so the custom wrapper
  */
new ScrollTrigger({}, document.body, wrapper);
```

It then adds the `scroll` listener to the `.wrap` div, and checks the `scrollTop` from `.wrap`. In most cases you'd leave `bindElement` alone.

**Comment by nightire** [comment]
@terwanerik Ah, that makes sense now. Thank you!
