### ISSUE TITLE
Elements slightly out of window not firing

### ISSUE THREAD

**Issue by daveswebdesigns** [terwanerik/ScrollTrigger#48]
Hi, thanks for this code, it's pretty handy. However, I have noticed one element which starts slightly off the window (with a translateX of -100 and a css rotation in this case) never fires on vertical scroll. I have tried doing xOffset but I think that's for horizontal scroll. 

Is it a limitation of the software that all elements must start wholly within the window on the x axis for them to activate with vertical scrolling?

**Comment by daveswebdesigns** [comment]
I found a workaround using animation instead of transition, it actually makes the css a little cleaner as all of the .*Out classes are just opacity: 0 and all of the action happens in the animation.

    dur = 1s
    ease = ease-in-out
    dist = 60px

    @keyframes fromLeftIn
        0%
            transform translate(-(dist),0)
        100%
            transform translate(0,0)
            opacity 1 !important

    .fromLeftIn
        animation fromLeftIn dur ease

    .fromLeftOut, .fromRightOut
        opacity 0 !important
Must be used with once:true or else it freaks out, but otherwise works good.

**Comment by daveswebdesigns** [comment]
The workaround above doesn't work if the element ends up slightly out of the window. I made a tiny edit to the scrolltrigger source code which works good if you're not using any horizontal scrolling

    this.left = function(_this){
        return function(){
            return 20;
        };
    }(this);

**Comment by terwanerik** [comment]
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.

**Comment by terwanerik** [comment]
I'd reckon this can be fixed in v1 by passing `{ offset: { element: { x: 20 } } }` as options for the out of bounds trigger, if this issue exists at all.

**Comment by light423** [comment]
hi! It's not working option.
I can not speak english  well. sorry~


const trigger = new ScrollTrigger({
    trigger: {
      once: true
    }
  });


Is it wrong???
