### ISSUE TITLE
Elements with negative offset invisible on first load if at top of viewport 

### ISSUE THREAD

**Issue by mtws** [terwanerik/ScrollTrigger#49]
If an example with a negative offset is at the top of the viewport it will not be considered visible until the page is scrolled.

```
<div data-scroll="offset(0,-200) once">
This element will have the class "invisible" until some scrolling occurs.
</div>
```

Example of the problem:
https://codepen.io/anon/pen/ReZrzv

**Comment by terwanerik** [comment]
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.

**Comment by terwanerik** [comment]
Updated the CodePen to v1.0.0, and this now works as expected. Closing this.
https://codepen.io/erikterwan/pen/pooOdar
