### ISSUE TITLE
Not working in Firefox or IE

### ISSUE THREAD

**Issue by PhilJ88** [terwanerik/ScrollTrigger#5]
Thanks for this, looks great, but seems to be only working fully in Chrome.
https://terwanerik.github.io/ScrollTrigger/

**Comment by terwanerik** [comment]
Alright looks like the legacy v0.1 version is working perfectly on FF

**Comment by terwanerik** [comment]
Fixed it for Firefox, download VM from Microsoft to test on IE right now!

**Comment by PhilJ88** [comment]
All good in IE11 (Win 7) now :)

**Comment by terwanerik** [comment]
Nice one! Closing this then. Would love to test on more browsers/versions. At least Safari, Chrome, Opera, Firefox and IE11 are all working!
