### ISSUE TITLE
mobile views

### ISSUE THREAD

**Issue by Hattop** [terwanerik/ScrollTrigger#50]
Hi i am beginner at coding and i  have problem on mobile device. It doesn´t display anythink what i want to animate. On PC it works. In another on scroll animate plugin they had possibility to forbidden animating when display width is less then 700px for example, it´s up to you. I want to ask if you have some solution for mobile device ?

**Comment by terwanerik** [comment]
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.

**Comment by terwanerik** [comment]
Avoiding animations on windows smaller than 700px can be done multiple ways, the simplest way would be to only add elements to the trigger when the viewport is at least 700px wide.

Closing this for now.

```javascript
const trigger = new ScrollTrigger()

if (window.innerWidth > 700) {
  trigger.add('[data-scroll]')
}
```
