### ISSUE TITLE
ScrollTrigger - callback not woking if element is already shown!

### ISSUE THREAD

**Issue by 7iomka** [terwanerik/ScrollTrigger#51]
I have a problem.
When user go from another section to coresponded with animated elements - all works ok.
But, when user reload page and browser brings him back to this section - is the situation same as if element is already shown for user.
For this use cases callbacks passed as data-scroll-hideCallback or data-scroll-showCallback will not work!
How to fix that?
https://codepen.io/7iomka/pen/yZZMxw

**Comment by vdorchan** [comment]
same problem

**Comment by vdorchan** [comment]
I have the same problem

**Comment by terwanerik** [comment]
v1.0 is coming soon, this will fix this issue. I'm still working on it, but quite busy at the moment. I would love to support Vue.js and React out of the box.

If you are brave you can already use the current draft of 1.0 @ https://github.com/terwanerik/ScrollTrigger/tree/v1.0

**Comment by ctlaux** [comment]
I have the same problem. Is v1.0 around the corner? I don't mean to rush you, if it is farther off I will try and build my own, as you suggested. Thanks for the library btw.

**Comment by Jeremboo** [comment]
I tried the v1.0 and it doesn't seem to work too. Any indications to try to fix this?

**Comment by terwanerik** [comment]
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.

**Comment by terwanerik** [comment]
Updated the codepen to use v1.0.0, now works as expected.

https://codepen.io/erikterwan/pen/qBBMVXQ

**Comment by ctlaux** [comment]
Hmm, I'm not sure how to map my old config to the new API... I have various `data-scroll-showCallback` in my html file, where do I put these for the new API? Maybe this should be documented in more detail and specifically for switching versions...

**Comment by terwanerik** [comment]
The scroll-showCallback can now be set either as a global callback, e.g. triggering by default on all triggers, or when adding a certain set of triggers;

**Global / default callback**
```javascript
const scrollTrigger = new ScrollTrigger({
  trigger: {
    toggle: {
      callback: {
        in: () => {
          // This is the same as setting a data-scroll-showCallback
          alert('in')
        },
        out: () => {
          // This is the same as setting a data-scroll-hideCallback
          alert('out')
        }
      }
    }
  }
})

scrollTrigger.add('[data-scroll]')
```

**Only for certain triggers**
```javascript
const trigger = new ScrollTrigger()
// Add simple triggers, without callback
trigger.add('[data-scroll]')

// Add triggers to the ScrollTrigger, only with attribute `data-scrollWithCallback`
trigger.add('[data-scrollWithCallback]', {
  toggle: {
    callback: {
      in: () => {
        alert('in')
      },
      out: () => {
        alert('out')
      }
    }
  }
})
```

Adding some documentation for upgrading from 0.x to 1.x sounds like a good idea, i'll add that to the roadmap.

**Comment by terwanerik** [comment]
Added [documentation on migrating from 0.x](https://github.com/terwanerik/ScrollTrigger#migrating-from-0x-to-1x)
