### ISSUE TITLE
overflow-y: scroll multi browser issues (doesn't show\animate)

### ISSUE THREAD

**Issue by dangelsaurus** [terwanerik/ScrollTrigger#62]
first an apology, I'm not the best with front end development, so go easy on me if I'm making a stupid mistake.

I've come across an issue where `overflow-y: scroll` on a `div` is causing ScrollTrigger not to fire, rather the element with the `data-scroll` attribute remains hidden.

I've test with Chrome 80, FireFox 74, and whatever Edge is at as of today...

Below is the link to the codepen...  I figured it might be better to just post a link to that instead of copy all the code here, but if not, I'll be happy to provide whatever answers y'all need from me.

Though here is a very rough layout.  `overflow-y: scroll` is on `main-container` and there's a lot of **flexbox** involved.  Removing  `overflow-y: scroll` fixes the problem, but of course messes up the layout.

```
<body>
  <div class="page">
    <div class="page-container">
      <div class="page-header"> 
      </div>
        <div class="main-container"> 
          <div class="article">
          </div>
          <div class="article" data-scroll>
          </div>
          <div class="article">
          </div>
        </div>
        <div class="page-footer">
        </div>
      </div>
    </div>
</body>
```
        

https://codepen.io/david-angel/pen/Poqrbxx

Thanks in advance (for your patience with me.)

**Comment by terwanerik** [comment]
You where using the 0.3.6 legacy version of ScrollTrigger. I've forked your pen and updated it to use the v1.x version.

https://codepen.io/erikterwan/pen/rNOwdYo

You can listen to scroll events inside a div containing `overflow-y: scroll`, this however means you need to tell ScrollTrigger where to listen for events, by default this is `window`, in the example i've set it to `document.querySelector('.main-container')`.
