### ISSUE TITLE
Add settings inline with [data-trigger]?

### ISSUE THREAD

**Issue by bigskillet** [terwanerik/ScrollTrigger#68]
Is it possible to add settings inline with [data-trigger] rather than setting them in the JS?

**Comment by terwanerik** [comment]
The preferred way to do this is have multiple (or different) data- attributes for this; say you would want some triggers to only fire once, and others to always fire (simple example); you would just add the new triggers by that attribute, and set the options in the JS. For custom settings per-element you could pass and parse json in a data-attribute.

```
// Via multiple data attributes
trigger.add('[data-triggerOnce]', { once: true })
trigger.add('[data-triggerAlways]', { once: false })

// With custom json parsing
trigger.add('[data-triggerOptions]')
trigger.query('[data-triggerOptions]').forEach(item => {
  const options = JSON.parse(item.element.getAttribute('data-triggerOptions'))
  item.once = options.once
  item.offset = options.offset
})

// <div data-triggerOptions='{"once":true,"offset": {"element":{"x":0,"y":50}, "viewport":{"x":0,"y":0} }}'
```
