### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by darthnorman** [terwanerik/ScrollTrigger#72]
Instead of using the ".visible" and ".invisible" class, try to prefix them so they don't interfere with Bootstrap's visibility classes.
https://getbootstrap.com/docs/4.5/utilities/visibility/

**Comment by dontskipnine** [comment]
You can modify the classes toggled via the options to get around that for such cases.

`let scrollTrigger = new ScrollTrigger({
        trigger: {
            toggle: {
                class: {
                    in: 'st-visible',
                    out: 'st-invisible',
                },
            },
        },        
    }),`

**Comment by terwanerik** [comment]
Thanks @dontskipnine, closing this.
