### ISSUE TITLE
explorer error

### ISSUE THREAD

**Issue by moko2man** [terwanerik/ScrollTrigger#73]
HI. Thanks for making this good plugin. 
It works good but doesn't on Explorer. Because there are some codes that Explorer does not support.
Although there's few people using Explorer,  but still some contries use Explorer.  I hope this support on Explorer. 

Thanks.

**Comment by terwanerik** [comment]
Hi! Thanks for the ticket. What errors are thrown on explorer? I don't have access to a windows device at the moment, so it's hard to test.

**Comment by moko2man** [comment]
"=>" function code makes error on Explorer.

**Comment by terwanerik** [comment]
You can run the code through Babel to transform the ES6, or use the (minified) pre-transpiled files inside the `dist` directory.
