### ISSUE TITLE
Can an on-screen element trigger an off-screen element?

### ISSUE THREAD

**Issue by jeremydouglass** [terwanerik/ScrollTrigger#74]
Is it possible for object id A, once on-screen, to trigger a show / hide class change on object id B, which is off-screen?

I'm guessing that ... perhaps ... the correct approach involves creating a callback for object A that passes B as an argument, like in this issue?

https://github.com/terwanerik/ScrollTrigger/issues/34

**Comment by terwanerik** [comment]
Yeah using a callback on 'trigger A' to change element B would be the way to go.

E.g:
```
{
    toggle: {
        callback: {
            in: () => {
                document.querySelector('.elementB').style.color = 'red'
            },
            out: () => {
                document.querySelector('.elementB').style.color = 'black'
            }
        }
    }
}
```

This will follow trigger A, if it comes into the viewport will make 'elementB' have red text; and when trigger A goes out of viewport black text.

Good luck! Closing this 👍

**Comment by jeremydouglass** [comment]
Thank you!
