### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by MikeHarrison** [terwanerik/ScrollTrigger#8]
Hi,

Your demo page is working great, but my implementation of ScrollTrigger is not working on iOS. I am trying to track down the issue now. I am calling jQuery before it, which I think may be a factor. The initial `invisible` class is being applied, but not the `visible`

**Comment by terwanerik** [comment]
Hm sounds strange, could you create a [http://stackoverflow.com/help/mcve](minimal, complete and verifiable example)? And upload that to codepen.io or something like that? Cannot reproduce this bug.

**Comment by MikeHarrison** [comment]
Here is a codepen, where I am seeing the same issue:

http://codepen.io/mikehdesign/pen/qNjJEj

**Comment by terwanerik** [comment]
Thanks! I'm looking into it.

**Comment by terwanerik** [comment]
Now fixed in v0.2.4 and v0.1.3

**Comment by MikeHarrison** [comment]
Great - thanks for the quick work!
