### ISSUE TITLE
Odd Issue with Toggle

### ISSUE THREAD

**Issue by influxweb** [terwanerik/ScrollTrigger#9]
First, this is a fantastic script. Thank you so much for publishing it.

I have noticed an odd issue when using the _toggle()_ attribute. If the class you are toggling has too many hyphens, the toggle will fail to execute. This could come up as an issue for those using a BEM pattern for their coding.

As an example, these class will work correctly:

- storefrontStoryInvisibleRight
- storefront-story-invisible-right
- storefrontSotry--invisible-right
- storefront-story--invisibleRight

However, the correct BEM structure for this will fail:

- storefront-story--invisible-right

I have scanned through the code, but I am stumped as to why this is happening.

**Comment by terwanerik** [comment]
That is some odd behaviour yeah, are you sure there are no weird/hidden unicode characters in the classname or something?

I've tested it using the following `data-scroll` tag, and that works perfectly:
`data-scroll="toggle(.storefront-story--visible-right, .storefront-story--invisible-right) addHeight"`

**Comment by influxweb** [comment]
I've tried retyping it and still get the same results. I did, however, notice that it does work correctly in Firefox but not in Chrome or Edge.

**Comment by terwanerik** [comment]
Thinking this might have anything to do with the .trim() function, only available in more modern browsers; i added a polyfill in this version; can you test it with that?

[ScrollTrigger.js.zip](https://github.com/terwanerik/ScrollTrigger/files/348238/ScrollTrigger.js.zip)

If the problem remains, could you create a [minimal, complete and verifiable example](http://stackoverflow.com/help/mcve) and upload that to [codepen](http://codepen.io)?

**Comment by influxweb** [comment]
So it looks like the issue was in the actual values in the classes being toggled. For the _invisible_ class, I was using a value of _translate(100vw,0)_. While this works just fine in all modern browsers, for some reason is tripping up the toggling of the class names. Once I changed the value to _translate(100%,0)_, everything works fine.

Thank you for your assistance with this matter.
